#!/usr/bin/env node

'use strict';
const fs = require('fs');
const fse = require('chokidar');

const [dirToWatch] = process.argv.slice(2);
const ignoreDotfilesReg = /(^|[\/\\])\../;

if (!dirToWatch && !fs.existsSync(dirToWatch)) {
	console.error('invalid args');
	process.exit(1);
}

fse.watch(dirToWatch, {ignored: ignoreDotfilesReg})
	.on('change', path => {
      console.log(path);
      process.exit(0);
	});
